<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Product;
use Illuminate\Database\Seeder;

class HairProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 6,
                'body_section_id' => null,

                'name' => 'Nourishing Shampoo',
                'description' => 'Cleanses & Strengthens',
                'price' => 350,
                'stock' => 90,
                'image' => 'images/hair/shampoo.png',
                'rating' => 5,
                'reviews' => 124,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 6,
                'body_section_id' => null,

                'name' => 'Repairing Conditioner',
                'description' => 'Nourishes & Repairs',
                'price' => 420,
                'stock' => 80,
                'image' => 'images/hair/conditioner.png',
                'rating' => 5,
                'reviews' => 96,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 6,
                'body_section_id' => null,

                'name' => 'Nourishing Hair Oil',
                'description' => 'Deeply Nourishes',
                'price' => 480,
                'stock' => 70,
                'image' => 'images/hair/Hair oil.png',
                'rating' => 5,
                'reviews' => 110,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 6,
                'body_section_id' => null,

                'name' => 'Intensive Repair Mask',
                'description' => 'Repairs & Strengthens',
                'price' => 450,
                'stock' => 60,
                'image' => 'images/hair/Hair Mask.png',
                'rating' => 5,
                'reviews' => 89,
            ],
            ///////////////////////////////////////////////
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 1,
                'body_section_id' => null,
                'name' => 'Curl Defining Shampoo',
                'description' => 'Defines & Hydrates Curls',
                'price' => 390,
                'stock' => 80,
                'image' => 'images/hair/curl-shampoo.png',
                'rating' => 5,
                'reviews' => 75,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 1,
                'body_section_id' => null,
                'name' => 'Curl Enhancing Cream',
                'description' => 'Soft & Bouncy Curls',
                'price' => 420,
                'stock' => 70,
                'image' => 'images/hair/curl-cream.png',
                'rating' => 5,
                'reviews' => 66,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 1,
                'body_section_id' => null,
                'name' => 'Curl Repair Mask',
                'description' => 'Deep Curl Treatment',
                'price' => 470,
                'stock' => 60,
                'image' => 'images/hair/curl-mask.png',
                'rating' => 5,
                'reviews' => 81,
            ],
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 1,
                'body_section_id' => null,
                'name' => 'Curl Leave-In Conditioner',
                'description' => 'Moisturizes & Defines',
                'price' => 410,
                'stock' => 75,
                'image' => 'images/hair/curl-leavein.png',
                'rating' => 5,
                'reviews' => 69,
            ],
            /////////////////////////////////
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 2,
                'body_section_id' => null,
                'name' => 'Smooth Shampoo',
                'description' => 'Silky Smooth Hair',
                'price' => 360,
                'stock' => 90,
                'image' => 'images/hair/smooth-shampoo.png',
                'rating' => 5,
                'reviews' => 90,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 2,
                'body_section_id' => null,
                'name' => 'Silk Conditioner',
                'description' => 'Smooth & Shine',
                'price' => 410,
                'stock' => 80,
                'image' => 'images/hair/silk-conditioner.png',
                'rating' => 5,
                'reviews' => 70,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 2,
                'body_section_id' => null,
                'name' => 'Shine Hair Serum',
                'description' => 'Instant Gloss',
                'price' => 440,
                'stock' => 75,
                'image' => 'images/hair/shine-serum.png',
                'rating' => 5,
                'reviews' => 65,
            ],
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 2,
                'body_section_id' => null,
                'name' => 'Anti-Frizz Spray',
                'description' => 'Smooth Finish',
                'price' => 350,
                'stock' => 80,
                'image' => 'images/hair/anti-frizz.png',
                'rating' => 5,
                'reviews' => 71,
            ],
            ///////////////////////////////////////
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 3,
                'body_section_id' => null,
                'name' => 'Wave Shampoo',
                'description' => 'Soft Natural Waves',
                'price' => 370,
                'stock' => 90,
                'image' => 'images/hair/wave-shampoo.png',
                'rating' => 5,
                'reviews' => 73,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 3,
                'body_section_id' => null,
                'name' => 'Sea Salt Spray',
                'description' => 'Beach Waves',
                'price' => 330,
                'stock' => 85,
                'image' => 'images/hair/sea-salt.png',
                'rating' => 5,
                'reviews' => 52,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 3,
                'body_section_id' => null,
                'name' => 'Wave Conditioner',
                'description' => 'Light Moisture',
                'price' => 390,
                'stock' => 70,
                'image' => 'images/hair/wave-conditioner.png',
                'rating' => 5,
                'reviews' => 64,
            ],
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 3,
                'body_section_id' => null,
                'name' => 'Wave Styling Cream',
                'description' => 'Defines Natural Waves',
                'price' => 420,
                'stock' => 70,
                'image' => 'images/hair/wave-cream.png',
                'rating' => 5,
                'reviews' => 62,
            ],
            ////////////////////////////////////
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 4,
                'body_section_id' => null,
                'name' => 'Repair Shampoo',
                'description' => 'Repairs Dry Hair',
                'price' => 390,
                'stock' => 70,
                'image' => 'images/hair/repair-shampoo.png',
                'rating' => 5,
                'reviews' => 84,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 4,
                'body_section_id' => null,
                'name' => 'Argan Hair Oil',
                'description' => 'Deep Nourishment',
                'price' => 480,
                'stock' => 60,
                'image' => 'images/hair/argan-oil.png',
                'rating' => 5,
                'reviews' => 95,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 4,
                'body_section_id' => null,
                'name' => 'Deep Repair Mask',
                'description' => 'Restores Damaged Hair',
                'price' => 450,
                'stock' => 65,
                'image' => 'images/hair/deep-mask.png',
                'rating' => 5,
                'reviews' => 77,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 4,
                'body_section_id' => null,
                'name' => 'Hydrating Conditioner',
                'description' => 'Moisture Boost',
                'price' => 410,
                'stock' => 80,
                'image' => 'images/hair/hydrating-conditioner.png',
                'rating' => 5,
                'reviews' => 82,
            ],
            /////////////////////////////////////////
            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 5,
                'body_section_id' => null,
                'name' => 'Purifying Shampoo',
                'description' => 'Controls Excess Oil',
                'price' => 360,
                'stock' => 90,
                'image' => 'images/hair/purifying-shampoo.png',
                'rating' => 5,
                'reviews' => 88,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 5,
                'body_section_id' => null,
                'name' => 'Scalp Scrub',
                'description' => 'Deep Cleansing',
                'price' => 400,
                'stock' => 70,
                'image' => 'images/hair/scalp-scrub.png',
                'rating' => 5,
                'reviews' => 63,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 5,
                'body_section_id' => null,
                'name' => 'Oil Control Spray',
                'description' => 'Fresh Hair All Day',
                'price' => 330,
                'stock' => 90,
                'image' => 'images/hair/oil-control.png',
                'rating' => 5,
                'reviews' => 57,
            ],

            [
                'category_id' => 2,
                'skin_type_id' => null,
                'hair_type_id' => 5,
                'body_section_id' => null,
                'name' => 'Balancing Conditioner',
                'description' => 'Lightweight Hydration',
                'price' => 390,
                'stock' => 85,
                'image' => 'images/hair/balancing-conditioner.png',
                'rating' => 5,
                'reviews' => 72,
            ],
        ]);
    }
}
